name: Run Tests
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Install Application
        run: poetry install

      - name: Run Tests
        run: pytest -vv