services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    restart: always
    command: npm run dev
    develop:
      watch:
        - path: ./frontend/package-lock.json
          action: rebuild
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
  backend:
    env_file:
      - ./backend/.env.docker
    container_name: backend
    build:
      context: ./backend
      args:
        DEV: true
    restart: always
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    develop:
      watch:
        - path: ./backend/poetry.lock
          action: rebuild
    environment:
      POSTGRES_DB: devdatabase
      POSTGRES_USER: devdbuser
      POSTGRES_PASS: secretSquirrel1984
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: devdatabase
      POSTGRES_USER: devdbuser
      POSTGRES_PASSWORD: secretSquirrel1984
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
