name: Run eslint and prettier for frontend

on:
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main
  push:
    paths:
      - "frontend/**"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run prettier
        run: npm run prettier
